### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by snifflezak** [FiercePunchStudios/HumbleKeysLibrary#1]
Perhaps a silly question but I just wanted to verify before doing something irreversible, this extension doesn't actually redeem keys when it populates your library does it? 
I have so many junk keys in my humble library which I would be horrified to see polluting my steam library. Thanks

**Comment by JustinHardage** [comment]
That's a great question! No, it doesn't redeem anything. I'm not even sure if Humble exposes an API to do so. It uses an endpoint that just enumerates all of your keys. I use it to build a database so I can stuff I own before picking up a game a third time in a new bundle.
